### ISSUE TITLE
keydown eventhandler for formatting/markdown while editing article

### ISSUE THREAD

**Issue by LanceKroepke** [HeavyHorst/knowledgebase#10]
eg

pressing CTRL+B for bold text (autoprinting **XX** with cofucs on XX)
pressing CTRL+I for cursive text (autoprinting *XX* with cofucs on XX)

etc.

**Comment by HeavyHorst** [comment]
This already works as expected.

https://github.com/NextStepWebs/simplemde-markdown-editor#keyboard-shortcuts

**Comment by LanceKroepke** [comment]
lurl
