### ISSUE TITLE
adminpanel - articles - add sorting feature

### ISSUE THREAD

**Issue by LanceKroepke** [HeavyHorst/knowledgebase#12]
clicking on a colums name could sort it descending/ascendig

clicking "Last changed" once whould show the ones recently changed first/on top.
(maybe this would be a gould default sorting also)

clicking it again would show the ones changed a long time ago

**Comment by HeavyHorst** [comment]
That would be possible. The date of the last change is stored in the last_modified field in the Article struct.

But there are a few things to consider.
 - At the moment the articles are sorted according to the creation date, which is also the order of the articles on disk (ULID as key in Boltdb). This allows us very effective 'pagination' with offset and limit.
 - If we want to sort by any other field, we have to load all articles in the backend and then sort them according to the desired criteria. Then we would have to apply limit and offset to the sorted items. This does not sound very effective, but should still be fast enough.
