### ISSUE TITLE
support/evaluate markdown visible for categories preview

### ISSUE THREAD

**Issue by LanceKroepke** [HeavyHorst/knowledgebase#2]
![unbenannt](https://cloud.githubusercontent.com/assets/9040475/25083139/a633ac54-2355-11e7-9797-73ec470f5d1d.png)

see screenshot

**bigger picture** should be bold

**Comment by LanceKroepke** [comment]
also support Linebreaks/paragraphs

maybe show truncated version as default
and show whole text on mouse hover

**Comment by HeavyHorst** [comment]
should be fixed with 
- 88f4702
- 6bbf0b5

if you still encounter problems then feel free to reopen this ticket.
