### ISSUE TITLE
allow un-/folding tree structure of the categories/articles overview

### ISSUE THREAD

**Issue by LanceKroepke** [HeavyHorst/knowledgebase#5]
e.g.
clicking on a folded category unfolds all subcategories into tree structure to further choose from

clikcing an unfolded one folds it into one category again

great for MORE AND MORE CATEGORIES/SUBCATEGORIES

caps :(

**Comment by HeavyHorst** [comment]
should be implemented with 715b09b73cf974fc10690a660eebc1f685173f90.
