### ISSUE TITLE
adminpanel - side by side preview - hyperlinks with parantheses in URL displaying wrong

### ISSUE THREAD

**Issue by LanceKroepke** [HeavyHorst/knowledgebase#7]
![unbenannt](https://cloud.githubusercontent.com/assets/9040475/25152360/fdb906a2-2488-11e7-9054-cf9ce20b87a3.png)

only adminpanel side by side preview for articles

viewing the article in knowledge base is fine. no trailing )

**Comment by HeavyHorst** [comment]
we use https://simplemde.com/ as markdown editor.
Please file an issue there.

**Comment by HeavyHorst** [comment]
Ah it seems to be an issue with CodeMirror.

**Comment by HeavyHorst** [comment]
We use simplemde as our Markdown editor which uses https://github.com/chjj/marked as the markdown renderer.

There seems to be an open issue already.
https://github.com/chjj/marked/issues/859
