### ISSUE TITLE
deadlink reporting system

### ISSUE THREAD

**Issue by LanceKroepke** [HeavyHorst/knowledgebase#9]
maybe a possibility to directly contact the author for issues regarding his categorie/article would be good.

like an issue tracker

if somewhere is a deadlink or a typo - well not a type, nobody cares about typos - there is something else wrong with the article, IMHO the author should know about and fix this this

**Comment by HeavyHorst** [comment]
I agree that this would be an useful feature but i think that an complete integrated issue tracker might be overkill.

A simple comment system in the articles might be enough?

**Comment by LanceKroepke** [comment]
maybe prefilled mailto:
"hi, there's an issue with your article XX:

FILL IN WHAT YOU WANTED TO REPORT"

that would serve at least the purpose of some kind of maintenance notification

**Comment by HeavyHorst** [comment]
Currently, the system doesn't know the users' email addresses. A small change to the data model would therefore be necessary. 

The system currently saves the authors of the last 3 changes. Should the email, in your opinion, be sent to all 3 or only to the last? Or should we save the initial creator of the article? 

A really simple comment system, as here in the issue, might be easier and clearer.
What is your opinion?

**Comment by LanceKroepke** [comment]
ah right I forgot that this is a collaboration kind of editing thing.

hmmm all authros would be overkill i think. even the last 3.
If one or maybe two of them made their changes 8 months ago, the article might've evolded into something else already.

I think such a feature then would be more appropraite in a big community with many active members.



since this is just an alpha, lets put this off to the future

**Comment by LanceKroepke** [comment]
are there any subcategories in github issues?

maybe a hyperlink to click in which you fill in WHAT YOU WANT TO REPORT.

that generates an issue under categorie "text/editing maintenace" or adds this label or smth.

maybe for this repository here. or we could set up a "virtual knowledge base editor repo"

**Comment by HeavyHorst** [comment]
out of scope for this project
